### ISSUE TITLE
[Task] Create a script to delete obsolete buckets from S3

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2021-thursday-repo#154]
**Is your feature request related to a problem? Please describe.**
While there exists a script to delete obsolete Azure resources, no such script exist for deleting obsolete S3 buckets (which we have a lot of). This should remedy that problem.

**Describe the solution you'd like**
Please create a script that lets the script runner delete obsolete buckets (and gives them the necessary information in order to make that decision)

**Describe alternatives you've considered**
Delete them one by one on the S3 console.

**Comment by lbrown51** [comment]
Resolves #154 

- This code adds a script for deleting obsolete buckets on S3
- Features
  - Lists all the buckets
  - Either lists the bucket owner's email or indicates that it doesn't have an owner
  - Either lists the objects in the bucket or indicates that it doesn't have objects
  - Gives the user the option to exit the script at any point and still proceed to delete previously scheduled buckets (you don't have to do it all at once)
- It doesn't automatically delete empty buckets or buckets that don't have tags (should it?)
- Must be run locally
- To run
  - Install required packages 
    - Navigate to Automation/S3 and use `pip install -r ./requirements.txt`
    - Also, you could just type `pip install boto3 colorama` 
  - From Automation/S3
    - Enter `python .\delete_s3_buckets.py --AccessKeyId access_key --SecretAccessKey secret`
    - You can set a custom region with `--RegionName region_name`
    - Use `python .\delete_s3_buckets.py -h` to get a super simple help message
    - You can find your Access Key ID and Secret Access Key in the message from Toddy last quarter. You can at least get the access key in the IAM management console on AWS (click: IAM -> Users -> Your email -> Security credentials), but won't be able to get the secret
- All the errors I'm aware of are taken care of using exceptions so there shouldn't be any troubleshooting necessary.

**Comment by lbrown51** [comment]
|**DATE**|**ACTIVITY**|**TIME**|
  |---|:---|:---|
  |2/11|Started doing research on AWS resources|45 minutes|
  |2/12|Continued doing research (especially on Boto3)|45 minutes|
  |2/12|Started initial research into writing Python scripts for the command line|45 minutes|
  |2/14|Started programming the actual functionality|60 minutes|
  |2/15|Continued writing actual functionality + started writing log messages|45 minutes|
  |2/15|Realized we didn't need log messages and switched them over to print statements|45 minutes|
  |2/16|Handled all the rest of the error handling and also most of the console statements|45 minutes|
  |2/17|Put all the work up on GitHub and began working on bugs.|30 minutes|
  |2/17|Realized that I needed to make everything work from the command line.|45 minutes|
  |2/17|More bugs in the PR.|30 minutes|
  |2/17|Wrote this PR|60 minutes|
