### ISSUE TITLE
[Task] Add a UI test for the React view /users to the Severless Artillery actions

### ISSUE THREAD

**Issue by lbrown51** [North-Seattle-College/ad440-winter2021-thursday-repo#192]
**Is your feature request related to a problem? Please describe.**
Basically as above, there is no SA test for the /users portion of the React site. We would like for performance tests (via serverless artillery) to be used on the /users view of the React site for the project.

**Describe alternatives you've considered**
We could manually test it, but that would make load testing very difficult.

**Comment by toddysm** [comment]
1. Create a separate action for the UI test only. Name it "UI Test /users". Action file name should be ui-tests-users.yml
2. In the action load the UI in the testing framework https://nscstrdevusw2thucommon.z5.web.core.windows.net/users
3. Take a screenshot
4. Save it to azure Storage container https://nscstrdevusw2thucommon.blob.core.windows.net/screenshots

The UI actions should be triggered last (after the other actions).
/users
/users/{user_id}
/users/{user_id}/tasks
/users/{user_id}/tasks/{task_id}

**Comment by lbrown51** [comment]
Resolves #192 
- This GitHub actions script will run when a pr is merged into the development branch
- How it works
  - Start doing the build and deploy job which runs on the latest ubuntu version
  - Checkout the repository
  - Setup the version of Node.js using environment variable NODE_VERSION
  - Install all the necessary npm packages, run `test_users` npm script, which (async)
    - Imports puppeteer
    - Opens a browser page
    - Goes to https://nscstrdevusw2thucommon.z5.web.core.windows.net/users
    - Takes a screenshot of that page and saves it to 
      - /test/results/ui-test-results/users/ui_users_year_month_day_hour-minute-second
    - Close browser
  - Deploy to Azure Container with
    - Name : screenshots
    - From the screenshot folder
    - Using the connection string in GitHub secrets under BLOB_STORAGE_CONNECTION_STRING
- The Node version, the path to the ui tests, and the path to the screenshots are not currently set to be secrets (I think that's what GitHub uses for all environment variables), but they easily could be if necessary)
- Both of those settings sit in the environment part of the deploy yaml script
- **Troubleshooting**: the only error I ran into was when the connection string was not correctly copied into the GitHub secrets area. If you start getting permission errors in Actions, that's probably what's causing it.
- Does not require any user-defined inputs
- Outputs are saved in resource group nsc-rg-dev-usw2-thursday, storage account nscstrdevusw2thucommon, container screenshots
- GitHub Actions output should look like [this](https://github.com/lbrown51/ad440-winter2021-thursday-repo/actions/runs/616096237)

**Comment by lbrown51** [comment]
|**DATE**|**ACTIVITY**|**TIME**|
  |---|:---|:---|
  |2/23|Researching + reading relevant code in the codebase|45 minutes|
  |2/24|Researching + looking at testing frameworks + slsart|45 minutes|
  |2/25|Realized I didn't need slsart at all|15 minutes
  |2/25|Realized I didn't need slsart at all|15 minutes|
  |2/27|Started programming the yaml file|45 minutes|
  |2/27|Started programming the test file|45 minutes
  |2/27|Debugging connection string issues|60 minutes|
  |3/1|Implemented a GitHub action to upload folder contents|45 minutes|
  |3/1|Rewrote to be plain azure cli script to upload|45 minutes|
  |3/1|Completed the test file|30 minutes|
  |3/3|Wrote this PR|40 minutes|
