### ISSUE TITLE
[Task] Create alerts for error 500 generated by the /users/{user_id} API – more than 30 errors 500 within 5 mins

### ISSUE THREAD

**Issue by yergu** [North-Seattle-College/ad440-winter2021-thursday-repo#201]

**Comment by yergu** [comment]
**Task Description**
-Create alerts for error 500 generated by the /users/{user_id} API – more than 30 errors 500 within 5 mins

**Expected Result** 
-When error 500 generated it sends email notification to my email
- This is the alert on Azure  portal

**Following are steps to create the Alert and expected outputs** 
1.	In Azure resource group select nsc-appins-dev-usw2-thursday
2.	In the Azure portal, select Monitor > Alerts.
3.	Select New alert rule in the upper-left corner of the Alerts window.
4.	Under Define alert condition, provide the required  information, and select Done
5.	Under Define alert details, provide the details:
6.	Under Action group, from the drop-down menu, specify the action group 
7.	To enable the rules after you create them, select Yes for the Enable rule upon creation option.
8.	Select Create alert rule.

**After I created the rule**
- I open this URL in my browser "https://nsc-fun-dev-usw2-thursday.azurewebsites.net/api/users/1" and kept on testing it and I get internal server error

 
![image](https://user-images.githubusercontent.com/56776980/109733458-f82baf00-7b73-11eb-8f68-7acbdd3928aa.png)

I 

- also tested in the azure portal like  this and I get same error message

![image](https://user-images.githubusercontent.com/56776980/109733654-61abbd80-7b74-11eb-9665-6a20892b727d.png)

**I get this email notification**
![image](https://user-images.githubusercontent.com/56776980/109737839-9bcc8d80-7b7b-11eb-8a63-06b7692eaa31.png)


![image](https://user-images.githubusercontent.com/56776980/109737834-98d19d00-7b7b-11eb-8618-e6cc44b38d45.png)


- This is the alert on Azure  portal

![image](https://user-images.githubusercontent.com/56776980/109734567-0f6b9c00-7b76-11eb-9994-1360996beee5.png)

**Comment by yergu** [comment]
Date | Activity | Time Spent
-- | -- | --
02/23/2021 | Setting up taxk|20 minutes
02/24/2021| research|2 hours
02/26/2021|reserach|2 hours 
02/28/2021|setup and configure the alert| 1hours
03/01/2021|troubleshoot |2 hours
03/02/2021 |testing and documentation|1hour

**Comment by ahmadafrasiyab** [comment]
@yergu This looks great. I hope we do not get 500 errors in reality 😃

**Comment by yergu** [comment]
Yes it doesn't have the error  unless I change the result code to 200 in the query

**Comment by jinudean** [comment]
@yergu It looks very great good job
