### ISSUE TITLE
Create alerts for error 500 generated by the  /users/{user_id}/task

### ISSUE THREAD

**Issue by jinudean** [North-Seattle-College/ad440-winter2021-thursday-repo#208]
create alert

**Comment by jinudean** [comment]
review in class video "monitoring part"and Microsoft document with activity log https://docs.microsoft.com/en-us/azure/azure-monitor/logs/log-analytics-tutorial

**Comment by jinudean** [comment]
search Microsoft Document "Log alerts in Azure Monitor" and copy query

![Screen Shot 2021-02-25 at 9 23 48 PM](https://user-images.githubusercontent.com/46363961/109406705-2620b180-7930-11eb-86f5-4353578b0454.png)

**Comment by jinudean** [comment]
Start to create nw alert rule with my own result code == "500"
with trashhold 30 in 5 mins

**Comment by jinudean** [comment]
# TEST HttpTriggerAPIUserIdTask 
Keep creating 500 Error but monitor tab shows success
![Screen Shot 2021-02-27 at 9 40 57 PM](https://user-images.githubusercontent.com/46363961/109409240-e2d13d80-7945-11eb-9f0d-1c09182ee268.png)

**Comment by jinudean** [comment]
I got email notification from Azure and confirmed fired alert on Azure
![Screen Shot 2021-02-27 at 6 50 56 PM](https://user-images.githubusercontent.com/46363961/109409270-36dc2200-7946-11eb-9c3e-9d9575358d8c.png)

![Screen Shot 2021-02-27 at 9 47 11 PM](https://user-images.githubusercontent.com/46363961/109409274-43f91100-7946-11eb-9108-7d511c3a09f1.png)

**Comment by jinudean** [comment]
Date | Activity | Time Spent
-- | -- | --
02/24/21 | Created Issue for 500 error 30times in 5 min on git hub | 15 min
02/25/21 | Research Microsoft Document log Analytics tutorial | 3 hrs
02/26/21 | Review unattandent class | 3 hrs
02/26/21 | Research Query language of Kusto | 4 hrs
02/27/21 | created alert and test | 3 hrs

**Comment by jinudean** [comment]
close issue

**Comment by ahmadafrasiyab** [comment]
Hi @jinudean it looks good to me and the email functionality is fine as well. I just have one suggestion as your query is checking the 500 code generally. We can narrow it down to this particular endpoint that you are testing and that way you will get an email only when your endpoint gives a 500 error and not when any of the four functions gives it. Feel free to check out my query to have an idea of what I am talking about. Rest looks good!
