### ISSUE TITLE
[Task] Implement script to create a VM

### ISSUE THREAD

**Issue by AlexSuth** [North-Seattle-College/ad440-winter2021-thursday-repo#22]
This pull request implements a script to create a Windows Virtual Machine with Microsoft Azure. The script references a `login.ps1` script, that automatically logs in to Azure using a Service Provider. 

Note: The end goal is to create an Ubuntu Virtual Machine similar to the one from our labs last quarter, but I 

Requirements:

- Powershell (Recommended 7.x or later)
   - Instalation instructions here: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.1
- Azure Powershell Module
   - Installation instructions: https://docs.microsoft.com/en-us/powershell/azure/install-Az-ps?view=azps-5.3.0
- Service Provider credentials
   - Tenant ID, Application ID, Application Secret, Subscription ID)

Testing instructions:

1.  Open a Powershell window and navigate to `.../ad440-winter2021-thursday-repo/Automation`
2. Once there, run the following command with all Parameters provided:
   `.\create_vm_script.ps1 <TenantID> <ApplicationID> <ApplicationSecret> <SubscriptionID> <ResourceGroupName> <VirtualNetworkName> <TemplateFilePath>`
3. The script will then ask the user for an Admin Username and Password (This will be changed in future edits to SSH Key)
4. If the Resource Group name provided already exists, the script will attempt to create a Virtual Machine in this group
5. If the Virtual Machine name already exists in the above resource group, the script will end.

Link to pull request: https://github.com/North-Seattle-College/ad440-winter2021-thursday-repo/pull/57

Time Tracking:

Date               | Activity | Time Spent
------------- | -------------     | ------------- 
1/8    | Development Environment Setup      | 1 hr
1/10  | Powershell Script Research              | 2 hr
1/13  | Code session 1: simple resource group creation | 2 hr 
1/16  | Code session 2: check if resources exist. Default parameters | 1.5 hr
1/18 | Code session 3: add templates. attempt to create Ubuntu template | 2 hr
1/20 | Code session 4: clean up and add Service Provider | 1.5 hr

**Comment by unicornsleuth** [comment]
You can update this - the code I used to successfully run the script was:
`.\create_vm_script.ps1 -tenantId <tenant id> -subscriptionId <subscription id> -applicationId <sp application id> -secret <sp secret> -rgName yaholl-test-rg -vmName yaholl-test-vm -adminUsername yaholl-username -adminPassword yaholl-password-123 `
