### ISSUE TITLE
Creating alerts for error 500 generated by the /users/{user_id}/tasks/{task_id} API

### ISSUE THREAD

**Issue by kevinles117** [North-Seattle-College/ad440-winter2021-thursday-repo#220]
Create alerts for error 500 generated by the /users/{user_id}/tasks/{task_id} API – more than 30 errors 500 within 5 mins

**Comment by kevinles117** [comment]
![image](https://user-images.githubusercontent.com/46364044/110045126-14a82280-7cff-11eb-884e-4ab8cfc3dda4.png)
![image](https://user-images.githubusercontent.com/46364044/110044923-c8f57900-7cfe-11eb-9caf-be7972780c39.png)

**Comment by kevinles117** [comment]
DATE | ACTIVITY | TIME
-- | -- | --
2/28 | Watched lecture and made sure I knew exactly what I needed to do | 2.5 hours
3/1 | Research Azure Function alerts | 1.5 hours
3/2 | Continued research of Azure Function alerts and Application Insights | 1.5 hours
3/4 | Tested API and forced 500 errors to get the email | 1.5 hours

Total Time Spent: 7 hours

**Comment by ahmadafrasiyab** [comment]
@kevinles117 this looks great. I hope you were able to resolve the code triggering part we discussed over slack.
