### ISSUE TITLE
Create alerts for error 500 generated by the /users/{user_id} API – API in AWS using CloudWatch – more than 10 errors 500 within 5 mins 

### ISSUE THREAD

**Issue by yergu** [North-Seattle-College/ad440-winter2021-thursday-repo#254]

**Comment by yergu** [comment]
**Is your feature request related to a problem? Please describe.**
This feature is to create alert functionality for 500 error generated for more than 30 times in 5 mins using AWS CloudWatch
**Describe the solution you'd like**
The idea is to create an alert  and send email notification  
**Additional context**
The testing for this was done against the users/userid endpoint as it was creating 500 errors.

Date | Activity | Time Spent
-- | -- | --
03/9/2021 | Setting up issue | 15 mins
03/11/2021 | Researching | 4 hour
03/14/2021 | Configuring the alert |  1hour
03/0115/2021 | testing and updating  | 1 hour
03/16/2021 | testing and updating  | 1 hour
03/19/2021 | testing and Fix errors| 1 hour

**Steps to create Alert**
**1. create SNS topics for the email notification**
![image](https://user-images.githubusercontent.com/56776980/111411036-1a0a5300-8697-11eb-88b5-5a98b9340ef0.png)


2. Configure the Alarm

To create a metric filter using the CloudWatch console
1.	Open the CloudWatch console at https://console.aws.amazon.com/cloudwatch/.
2.	In the navigation pane, choose Log groups.
3.	Choose the name of the log group.
4.	Choose Actions, Create metric filter.
5.	For Filter pattern, enter the filter pattern to use  “Error 500”
6.	Click on test your filter pattern, under Test Pattern, 
7.	Choose Next, and then enter a name for the filter.
8.	Under Metric details,  Enter the   Metric namespace,and Metric value, 
9.	confirm metric filter was created then check box right upper corner
10.	confirm "create alarm" is clickable
11.	In the Create alarm window specify the metric and conditions 
12.	Put threshold 10
13.	In Select an SNS topic section select an existing SNS topic or create new topic (In my case since I already Created the topic I selected “Yergu Topic”
14.	Then Click Next
15.	In the Create Alarm window Specify Name and description of Alarm and Then click Next
Triger the Error  by changing the DB password or name 
16.	Go to lambada Function and test the ApI if the Error created
**Expected Result**

**1, Alarm is created**
![image](https://user-images.githubusercontent.com/56776980/111760410-e9bfe180-885b-11eb-917b-c95dec4cc86f.png)

**2. And Email notification send**
![image](https://user-images.githubusercontent.com/56776980/111760597-2095f780-885c-11eb-8208-c31cf81d207f.png)

**Comment by jinudean** [comment]
nice job y
