### ISSUE TITLE
Create Alerts for error 500 generated by the /user/{user_id}/tasks

### ISSUE THREAD

**Issue by jinudean** [North-Seattle-College/ad440-winter2021-thursday-repo#267]
get email alerts from AWS when more than 10 errors 500 within 5mins

**Comment by jinudean** [comment]
first of all, I need to create clone lambda function to trigger alarm fro 500 error

**Comment by jinudean** [comment]
I created "Status code" but i could not count error on metric graph

**Comment by jinudean** [comment]
"Status code : 500" is not on message section of log

**Comment by jinudean** [comment]
Create Error Lambda function of HttpTriggerApiUsersUseridTasks then confirmed Error count on function monitor on metric
![Error metric](https://user-images.githubusercontent.com/46363961/111573920-af294c80-8768-11eb-977c-23391dd767d6.png)

**Comment by jinudean** [comment]
review filter syntax document from AWS
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html

**Comment by jinudean** [comment]
Click View logs in "ClouldWatch"
![Screen Shot 2021-03-17 at 9 44 06 PM](https://user-images.githubusercontent.com/46363961/111574613-0f6cbe00-876a-11eb-8f1b-be68108a739f.png)

**Comment by jinudean** [comment]
# click "metric filters"
![Screen Shot 2021-03-17 at 9 45 53 PM](https://user-images.githubusercontent.com/46363961/111574746-4e027880-876a-11eb-8240-e53a69b87a0a.png)

# Create metric filter
![Screen Shot 2021-03-17 at 9 48 20 PM](https://user-images.githubusercontent.com/46363961/111574889-8dc96000-876a-11eb-8206-d241ae459fd2.png)

# Type into filter pattern "ERROR 500"  
# test pattern with log which one has "ERROR 500"
# click Test pattern and confirmed filter working with log event the click next
# fill out create filter name 
# review and create

**Comment by jinudean** [comment]
# confirm metric filter was created then check box right upper corner
# confirm "create alarm" is clickable
# new window open
![Screen Shot 2021-03-17 at 9 57 34 PM](https://user-images.githubusercontent.com/46363961/111575533-ce75a900-876b-11eb-8bab-d998b02e8972.png)

# enter " 10 " trashhold value then next
# select Create new topic then enter topic name and enter email address
![Screen Shot 2021-03-17 at 10 00 07 PM](https://user-images.githubusercontent.com/46363961/111575829-74291800-876c-11eb-974b-228fc78001b1.png)

# next page show up "Alarm name" and "Alarm description"
![Screen Shot 2021-03-17 at 10 03 33 PM](https://user-images.githubusercontent.com/46363961/111575911-a2a6f300-876c-11eb-9221-544b8e40ebd8.png)

**Comment by jinudean** [comment]
# Test going back to function test page then create error least 11 times to create alarm 
# confirmed Error create and it hit alarm. Alarm show up action triggered 
![Screen Shot 2021-03-18 at 7 33 08 PM](https://user-images.githubusercontent.com/46363961/111723499-dc393600-8820-11eb-8ac8-c3ad3dd9a27b.png)

**Comment by jinudean** [comment]
# Confirm email SNS notice from AWS
![Screen Shot 2021-03-18 at 7 10 42 PM](https://user-images.githubusercontent.com/46363961/111723558-f3782380-8820-11eb-8ba3-f0181a692f50.png)

**Comment by jinudean** [comment]
Date | Activity | Time Spent
-- | -- | --
03/11/21 | Research AWS alarm clould watch | 2 hrs
03/12/21 | Research AWS Document | 2 hrs
03/13/21 | Research AWS metric filter | 2 hrs
03/16/21 | Filter pattern make for [ERROR] | 4 hrs
03/18/21 | ReCreated alarm with "ERROR 500 " filter pattern | 1 hrs

**Comment by yergu** [comment]
Hi Jin, I reviewed your work , Everything looks  Looks Fine, Good Job!
