### ISSUE TITLE
[Task] Create K8 Cluster in Azure w/ Artillery

### ISSUE THREAD

**Issue by gillilands19** [North-Seattle-College/ad440-winter2021-thursday-repo#28]
**Is your feature request related to a problem? Please describe.**
No, since nothing can be done with artillery for Kubernetes, it would just be considered a simple request to create a Kubernetes cluster.

**Describe the solution you'd like**
Just simply create a Kubernetes cluster

**Describe alternatives you've considered**
Since nothing can be done with artillery for Kubernetes, I read an article on artillery.io.  One can actually use AWS fargate and/or ECS with artillery. Maybe that can be something to do for the future?  I only thought about that because I noticed that serverless artillery seems to use AWS.

Link to the article: https://artillery.io/docs/guides/guides/running-tests-with-artillery-pro.html#Overview

**Additional context**
Creation of the Kubernetes cluster was on Azure portal.  Also, you might receive an error message that the validation did not go through because of something wrong with the service principal.  You might want to be patient and simply go back to the validation tab and repeat going through validation, integration, tags, etc. again.

**Comment by chonger878** [comment]
**Date             Activity                                                                                                   Time**
1/13/21          Installed serverless/serverless-artillery into machine                              10 mins

**Comment by chonger878** [comment]
Process for creating a Kubernetes cluster on Azure Portal:
1.) Login to Azure Portal with your credentials

**Comment by chonger878** [comment]
Activities Log Documentation

Date Activity Time
1/13/21 Installed serverless/serverless-artillery into machine 10 mins
1/18/21 Failed attempt at Building test Kubernetes cluster on Azure Portal 5 mins
1/18/21 Successfully built test Kubernetes cluster on Azure Portal 5 mins
1/19/21 Successful run through of creating Kubernetes cluster on Azure Portal 20 mins
and documentation of process
