### ISSUE TITLE
/taskId PUT failure

### ISSUE THREAD

**Issue by unicornsleuth** [North-Seattle-College/ad440-winter2021-thursday-repo#288]
**Describe the bug**
A PUT request fails to update, because of a bug in the code - expects 3 positional arguments, but receives 4
After I quickly/temporarily made this fix, I found that a PUT (and also patch, delete) does not invalidate the particular cache for that task.

**To Reproduce**
1. In VSCode, run the Azure functions
2. In Postman, run a GET on http://localhost:7071/api/users/1/tasks
3. Take the first taskId you see (for me, it was 2) and run a GET on http://localhost:7071/users/1/tasks/2 
4. Create a PUT request on http://localhost:7071/users/1/tasks/2 with the raw body:
```
{
   "title": "title",
   "description": "description",
   "dueDate": "03/04/21 12:12:12",
   "completed": "0",
   "completedDate": "04/04/21 12:12:12"
}
```
5. See error

**Expected behavior**
You should see "Error: update() takes 3 positional arguments but 4 were given"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCode
 - Postman

**To Reproduce 2nd Part**
1. You can easily fix this bug by removing the ",r" from line 308 of the /taskId init file
2. Save & reload functions
3. Run the PUT request from before (step 4)
4. Run the GET request from before (step 3) and see that the data has not been updated
5. Check in VSCode, and see that the output says "Cache cleared" AND "Returned data from cache"
6. Run the GET request from before (step 2) and see that the data has, in fact, been updated. 

**Additional context**
We should have a cache for each task that has been queried, of the form "users:{userId}:tasks:{taskId}"
The caches *are* being created for these, but they are not being cleared when PUT/PATCH/DELETE is run on the task.
The code needs to be reworked to invalidate those particular caches *as well as* the "users:{userId}:tasks" cache on each update.

**Comment by jaguiniga** [comment]
Date | Activity | Time Spent
-- | -- | --
03/219/2021 | Testing Bug issue | 20 mins
03/21/2021 | Researching Solutions | 1 hour
03/22/2021 | Testing Solutions | 2 hours
03/23/2021 | Testing deployment | 1 hour
03/24/2021 | Creating PR | 30 mins

How to Test :
    - Open project in VS Code
    - Click on the debugger icon on the left hand side tool bar in VS Code
    - Set up environment for testing using python pathway
    - Run the Azure functions  In VS Code (Terminal should open and show logs and URL links for testing of functions)
    - Open PostMan and paste URL links to functions and make GET for userId taskId request to cache 
    - Check Redis Server Cache for saved data
    - Run DELETE request and refresh Cache and the data should be deleted. Same with PUT Request
   
 Description:
    Fixed the parameter bug in the PUT method. Took r (redis conneciton) out of the PUT method parameters. Solving the issue. Fixed the delete cache issue by changing the parameters in the invalidate function. Added the parameters key, userId, and taskId. Added the function call in the main where the PUT and DELETE functions are called.
