### ISSUE TITLE
[Task] Implement script to create an Azure Storage account

### ISSUE THREAD

**Issue by theanticrumpet** [North-Seattle-College/ad440-winter2021-thursday-repo#7]
Task from Sprint 1 doc: Team 2, task 5.

**Comment by theanticrumpet** [comment]
Required:
- Powershell
- Powershell module Az version 0.7 or later:  `Get-InstalledModule -Name "Az"` to check
    - See [Introducing the Azure Az PowerShell Module](https://docs.microsoft.com/en-us/powershell/azure/install-Az-ps?view=azps-5.3.0)

Script can be found in [REPO]\Automation\create_Azure_StorageAccount.ps1

Open up a PowerShell window
Sign in to Azure through PowerShell: `Connect-AzAccount` Follow instructions on screen
In the Powershell window type "&" space and then drag the script file, this should auto fill in the command `& "[PATH TO FILE]\create_Azure_StorageAccount.ps1"`
Run the command
You will see basic Write-Host output as script runs
Resource Group and Storage Account names are declared as variables in script
Script will check if resource group exists, then create it if it doesn't
Script will check if a Storage Account with that name exists
- If it doesn't exist, script will create a storage account in the above resource group in US West 2 configured for Read-Access geo-redundant storage, using general purpose V2 storage.
- If it does exist print a message saying so

Output of script also saved in a text file `create_Azure_StorageAccountlog.log`

**Comment by theanticrumpet** [comment]
### Time tracking:
| **Date** | **Activity** | **Time Spent** |
|----------|-------------|-----------------|
| 8/Jan | Researching PowerShell script writing | 30 minutes |
| 8/Jan | Writing/Researching/Testing Storage Account scripting | 1.5 hours |
| 8/Jan | Researching PowerShell logging | 15 minutes |

**Comment by 1jc** [comment]
Looks good reviewed 1jc Team 2.  Okay to do Pull
